# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    http_client:
        default_options:
            # 中国地区需要配置代理才能访问 OpenAI API
            proxy: '127.0.0.1:7890'
            # 如果代理需要认证，可以使用 'http://user:password@proxy:port' 格式
            cafile: '%kernel.project_dir%/ssl/cacert.pem'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
